- name: Install nginx
  dnf:
    name: nginx
    state: present

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Health check
  uri:
    url: "http://localhost"
    status_code: 200
  register: result
  retries: 5
  delay: 3
  until: result.status == 200
