- name: Precheck
  hosts: all
  become: yes
  roles:
    - precheck

- name: Patch DB Tier
  hosts: db
  become: yes
  serial: 1
  roles:
    - rhel_patching

- name: Patch App Tier
  hosts: app
  become: yes
  serial: 1
  roles:
    - rhel_patching

- name: Patch Web Tier
  hosts: web
  become: yes
  serial: 1
  roles:
    - lb_management
    - rhel_patching
    - postcheck
